server: 
  port: 9005
spring: 
  application:  
    name: socialWeb-gathering #指定服务名
  datasource:  
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.116.128:3306/socialWeb_gathering?characterEncoding=UTF8
    username: root
    password: root
  jpa: 
    database: MySQL
    show-sql: true
